version: "3.7"
services:
  alaquorum:
    build: ./alaquorum
    volumes:
      - "./alaquorum/data_dir:/root/alastria/data"
    ports:
      - "21000:21000"
  openresty:
    build: ./openresty
#    depends_on:
#      - alaquorum
    volumes:
      - "./openresty/nginxconf:/usr/local/openresty/nginx/conf"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "22000:22000"