version: "3.7"
services:
  alaquorum:
    build: ./alaquorum
    volumes:
      - "./alaquorum/data_dir:/root/alastria/data"
  accesspoint:
    build: ./accesspoint
#    depends_on:
#      - alaquorum
    volumes:
      - "./accesspoint/nginxconf:/etc/nginx"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "22000:22000"
  openresty:
    build: ./openresty
#    depends_on:
#      - alaquorum
    volumes:
      - "./openresty/nginxconf:/usr/local/openresty/nginx/conf"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "22000:22000"